import type { ReactNode } from 'react';
import type { AgentUsage, ContentBlock } from '@/types';
import type { ChatEvidenceSource, ToolCallInfo } from './types';
import type {
  PmClaimEvidence,
  PmConflictGraph,
  PmConflictRow,
  PmEvidenceTreeNode,
  PmReportArtifact,
  PmSearchUsageSummary,
} from './chatCore.pmTypes';

export interface DisplayMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string | ContentBlock[];
  /** Millisecond timestamp used by the chat bubble header. */
  timestamp?: number;
  /** Compatibility with API records that expose ISO/camel-case creation time. */
  createdAt?: string | number | null;
  toolCalls?: ToolCallInfo[];
  evidenceSources?: ChatEvidenceSource[];
  thinking?: string | null;
  thinkingLoading?: boolean;
  thinkingDurationMs?: number;
  isStreaming?: boolean;
  isBookmarked?: boolean;
  replyTo?: string;
  projectIds?: string[];
  pmTaskId?: string;
  pmTaskStatus?: string;
  pmReport?: PmReportArtifact;
  pmSearchUsage?: PmSearchUsageSummary;
  traceEvents?: Record<string, unknown>[];
  modelName?: string;
  judgeModel?: string;
  winnerModel?: string;
  winnerReason?: string;
  /** Persisted multi-model run used to render the auditable round transcript. */
  adversarialRunId?: string;
  /** Persisted data-attribution task used by the SQL/evidence audit panel. */
  attributionTaskId?: string;
  /** Parent turn id used to associate durable unified-agent metadata. */
  superAssistantTurnId?: string;
  /** Local slash-command output; it was not generated by the active model. */
  localCommand?: boolean;
}

export interface StreamingHandlers {
  onSessionActivated?: (meta: any) => void;
  onConfigHotReload?: (meta: any) => void;
  onThinkingStart?: () => void;
  onThinkingDelta?: (text: string) => void;
  onThinkingEnd?: () => void;
  onTextBlockStart?: () => void;
  onText?: (text: string) => void;
  onTextBlockEnd?: () => void;
  onToolUseStart?: (index: number, id: string, name: string) => void;
  onToolInputDelta?: (index: number, partialJson: string) => void;
  onToolUseEnd?: (index: number) => void;
  onToolResult?: (
    index: number,
    toolName: string,
    input: string,
    output: any,
    isError: boolean,
    durationMs?: number,
  ) => void;
  onToolCall?: (tool: any) => void;
  onUsage?: (usage: AgentUsage) => void;
  onPmStage?: (stage: {
    stage: string;
    status: string;
    attempt?: number;
    detail?: Record<string, unknown>;
  }) => void;
  onPmQuality?: (quality: {
    passed: boolean;
    deliverable?: boolean;
    quality_level?: string;
    has_tool_calls: boolean;
    tool_call_count: number;
    citation_count: number;
    domain_count?: number;
    claim_count?: number;
    claim_alignment_ok?: boolean;
    citations?: string[];
    domains?: string[];
    claim_alignment?: PmClaimEvidence[];
    evidence_tree?: PmEvidenceTreeNode[];
    conflict_matrix?: PmConflictRow[];
    conflict_graph?: PmConflictGraph;
    missing: string[];
    suggestions: string[];
  }) => void;
  onStreamEnd?: (
    iterations: number,
    usage: any,
    fullText: string | undefined,
    finalThinking: string | undefined,
    meta?: {
      pm_quality?: {
        passed: boolean;
        deliverable?: boolean;
        quality_level?: string;
        has_tool_calls: boolean;
        tool_call_count: number;
        citation_count: number;
        domain_count?: number;
        claim_count?: number;
        claim_alignment_ok?: boolean;
        citations?: string[];
        domains?: string[];
        claim_alignment?: PmClaimEvidence[];
        evidence_tree?: PmEvidenceTreeNode[];
        conflict_matrix?: PmConflictRow[];
        conflict_graph?: PmConflictGraph;
        missing: string[];
        suggestions: string[];
      };
      pm_report?: PmReportArtifact;
      streamMode?: 'token_delta' | 'tool_interleaved' | 'final_text_typewriter' | 'cancelled' | string;
      telemetry?: {
        firstTokenLatencyMs?: number | null;
        elapsedMs?: number;
        fallbackTypewriter?: boolean;
        textDeltaCount?: number;
        toolInterleaved?: boolean;
        cancelled?: boolean;
        searchMode?: string;
      };
    },
  ) => void;
  onError?: (error: string) => void;
}

export interface ChatCoreProps {
  sessionSource: 'chat' | 'agent' | 'pm';
  emptySessionText: string;
  noSessionPlaceholder?: {
    title: string;
    description: string;
    emoji: string;
  };
  topBarExtra?: ReactNode;
  topBarActions?: ReactNode;
  rightPanel?: ReactNode;
  rightPanelOpen?: boolean;
  onScrollToBottom?: () => void;
  onStreamingChange?: (streaming: boolean) => void;
  onBeforeStream?: (msg: DisplayMessage) => void;
  onStreamFinished?: (
    finalMsg: DisplayMessage,
    completedToolCalls: ToolCallInfo[],
    resolvedThinking: string,
  ) => void;
  onUsage?: (usage: {
    inputTokens: number;
    outputTokens: number;
    estimatedCostUsd?: number;
  }) => void;
  onSessionCreated?: (sessionId: string) => void;
  /** Fires whenever the active session changes (created, selected, or cleared). */
  onActiveSessionChange?: (sessionId: string | null) => void;
  onAbortRef?: (fn: (() => void) | null) => void;
  sidebarWidth?: number;
  showConfigTags?: boolean;
  messageListProps?: React.HTMLAttributes<HTMLDivElement>;
  inputAreaProps?: React.HTMLAttributes<HTMLDivElement>;
  inputPlaceholder?: string;
  inputHintBar?: ReactNode;
  inputToolbarExtra?: ReactNode;
  selectedModel?: string;
  /**
   * When true, outgoing messages are sent through the unified Super_Assistant
   * endpoint (`POST /super-assistant/messages`) instead of the default
   * per-session streaming path. The backend AOS_Router dispatches each message
   * to the best capability (ai_chat / nl2sql / pm_assistant / super_adversarial)
   * and returns a grounded answer, which the shell renders with the shared
   * streaming presentation (Req 1.1 / 1.6 / 8.2).
   */
  superAssistantEndpoint?: boolean;
}
